enum UnitType {
    infantry,
    cavalry,
    villager
}

enum ArmourClass {
    infantry,
    cavalry,
    uniqueUnit,
    eagleWarrior,
    camel,
    warElephant,
    mameluke,
    condottiero,
    spearman
}

enum UnitId {
    champion = "champion",
    condottiero = "condottiero",
    halbardier = "halbardier",
    hussar = "hussar",
    eliteEagleWarrior = "eliteEagleWarrior",
    eagleWarrior = "eagleWarrior",
    eliteHuskarl = "eliteHuskarl",
    huskarl = "huskarl",
    eliteJaguarWarrior = "eliteJaguarWarrior",
    jaguarWarrior = "jaguarWarrior",
    eliteTeutonicKnight = "eliteTeutonicKnight",
    teutonicKnight = "teutonicKnight",
    eWoadRaider = "eWoadRaider",
    woadRaider = "woadRaider",
    eShotel = "eShotel",
    shotel = "shotel",
    eKarambit = "eKarambit",
    karambit = "karambit",
    eDismountedKonnik = "eDismountedKonnik",
    dismountedKonnik = "dismountedKonnik",
    twoHandedSwordsman = "twoHandedSwordsman",
    xolotl = "xolotl",
    knight = "knight",
    cavalier = "cavalier",
    paladin = "paladin",
    camel = "camel",
    heavyCamel = "heavyCamel",
    imperialCamel = "imperialCamel",
    eBattleElephant = "eBattleElephant",
    battleElephant = "battleElephant",
    eSteppeLancer = "eSteppeLancer",
    steppeLancer = "steppeLancer",
    eLeitis = "eLeitis",
    leitis = "leitis",
    eKeshik = "eKeshik",
    keshik = "keshik",
    eKonnik = "eKonnik",
    konnik = "konnik",
    eBoyar = "eBoyar",
    boyar = "boyar",
    eSamurai = "eSamurai",
    samurai = "samurai",
    eWarElephant = "eWarElephant",
    warElephant = "warElephant",
    eCataphract = "eCataphract",
    cataphract = "cataphract",
    eBerserk = "eBerserk",
    berserk = "berserk",
    eMagyarHuszar = "eMagyarHuszar",
    magyarHuszar = "magyarHuszar",
    eKamayuk = "eKamayuk",
    kamayuk = "kamayuk",
    villager = "villager",
    pikeman = "pikeman",
    tarkan = "tarkan",
    eTarkan = "eTarkan"
}

enum Side {
    left,
    right
}